services:
  mariadb:
    container_name: mariadb
    build:
      dockerfile: Dockerfile
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - inception_network
    secrets:
      - db_host
      - db_password
      - db_root_password
      - dbname
      - dbuser
      - wp_admin_email
      - wp_admin_password
      - wp_admin_user
      - wp_email
      - wp_host 

  wordpress:
    container_name: wordpress
    build:
      dockerfile: Dockerfile
      context: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception_network
    env_file:
      - .env
    secrets:
      - db_host
      - db_password
      - db_root_password
      - dbname
      - dbuser
      - wp_admin_email
      - wp_admin_password
      - wp_admin_user
      - wp_email
      - wp_host 
  
  nginx:
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - inception_network
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/data/mariadb_data #In case is not macOS, change the path
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/${USER}/data/wordpress_data #In case is not macOS, change the path

networks:
  inception_network:
    driver: bridge
    name: inception_network

secrets:
  db_host:
    file: ${FILE}db_host.txt
  db_password:
    file: ${FILE}db_password.txt
  db_root_password:
    file: ${FILE}db_root_password.txt
  dbname:
    file: ${FILE}dbname.txt
  dbuser:
    file: ${FILE}dbuser.txt
  wp_admin_email:
    file: ${FILE}wp_admin_email.txt
  wp_admin_password:
    file: ${FILE}wp_admin_password.txt
  wp_admin_user:
    file: ${FILE}wp_admin_user.txt
  wp_email:
    file: ${FILE}wp_email.txt
  wp_host:
    file: ${FILE}wp_host.txt